name: CI
on:
  - push
  - pull_request
permissions: {}
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version:
          - 4
          - 6
          - 8
          - 10
          - 12
          - 14
          - 16
          - 18
          - 20
          - 22
          - 24
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm publish --tag=${{ contains(github.ref, '-rc') && 'rc' || 'latest' }}
